# -*- coding: utf-8 -*-
"""สำเนาของ โครงงาน

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9s7WAUWYrIpvf2NZWzeLTN95HKtOvMo
"""

# ติดตั้งไลบรารีที่จำเป็น
#!pip install opencv-python-headless numpy pillow matplotlib

# นำเข้าไลบรารี
import cv2
import numpy as np
from PIL import Image
from google.colab import files
import matplotlib.pyplot as plt

# อัปโหลดภาพ
uploaded = files.upload()

# โหลดภาพจากไฟล์ที่อัปโหลด
for filename in uploaded.keys():
    pil_image = Image.open(filename).convert('RGB')
    image = np.array(pil_image)

# แปลงภาพจาก RGB เป็น HSV
hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

# กำหนดช่วงสีของสารเรืองแสง (สีฟ้าเรืองแสงจากภาพที่คุณอัปโหลด)
lower_fluorescent = np.array([105, 80, 160])   # Hue ~105 = ฟ้า
upper_fluorescent = np.array([130, 255, 255])  # Hue ~130 = ฟ้าเข้ม

# สร้าง mask เพื่อแยกบริเวณที่มีสารเรืองแสง
mask = cv2.inRange(hsv, lower_fluorescent, upper_fluorescent)

# คำนวณเปอร์เซ็นต์พื้นที่ fluoresence
fluorescent_area = cv2.countNonZero(mask)
total_area = image.shape[0] * image.shape[1]
percentage = (fluorescent_area / total_area) * 100

# แบ่งภาพตามสัดส่วนของมือจากโดนัทชาร์ต
height, width = mask.shape
zones = {
    "ฝ่ามือ": mask[int(height*0.35):int(height*0.65), int(width*0.25):int(width*0.75)],
    "นิ้วมือ": mask[0:int(height*0.35), int(width*0.2):int(width*0.8)],
    "หลังมือ": mask[int(height*0.35):int(height*0.65), 0:int(width*0.25)],
    "ข้อมือ": mask[int(height*0.65):, int(width*0.25):int(width*0.75)],
    "นิ้วหัวแม่มือ": mask[int(height*0.2):int(height*0.5), int(width*0.8):],
    "หลังนิ้วหัวแม่มือ": mask[int(height*0.2):int(height*0.5), 0:int(width*0.2)],
    "ระหว่างนิ้ว": mask[int(height*0.2):int(height*0.35), int(width*0.3):int(width*0.7)]
}

recommendations = []
zone_results = {}

for zone_name, zone_mask in zones.items():
    zone_area = zone_mask.shape[0] * zone_mask.shape[1]
    zone_fluorescent = cv2.countNonZero(zone_mask)
    zone_percent = (zone_fluorescent / zone_area) * 100
    zone_results[zone_name] = zone_percent
    if zone_percent > 5:  # ถ้ามีสารเรืองแสงเกิน 5% ถือว่ายังไม่สะอาด
        recommendations.append(f"- ควรล้างบริเวณ **{zone_name}** ให้สะอาดขึ้น ({zone_percent:.1f}%)")

# แสดงผล
print(f"\n🔍 พบสารเรืองแสงประมาณ {percentage:.2f}% ของพื้นที่ภาพ\n")
if recommendations:
    print("🧼 คำแนะนำในการล้างมือเพิ่มเติม:")
    for rec in recommendations:
        print(rec)
else:
    print("✅ มือสะอาดดี ไม่พบสารเรืองแสงในระดับที่ต้องล้างเพิ่ม")

# แสดงภาพต้นฉบับและ mask
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(image)
plt.title("ภาพต้นฉบับ")

plt.subplot(1,2,2)
plt.imshow(mask, cmap='gray')
plt.title("บริเวณที่มีสารเรืองแสง")
plt.show()
